name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/cellular_connection_2_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/wifi_2_x2.svg
  - assets/images/success_png_transparent_images_transparent_success_clipart_png_1.jpeg
  - assets/vectors/cellular_connection_1_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/vectors/wifi_5_x2.svg
  - assets/images/logo.png
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/cellular_connection_3_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/vectors/rectangle_1_x2.svg
  - assets/vectors/battery_4_x2.svg
  - assets/vectors/rectangle_8_x2.svg
  - assets/vectors/subtract_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/cellular_connection_4_x2.svg
  - assets/vectors/battery_3_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/cellular_connection_5_x2.svg

