name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/rectangle_11.jpeg
  - assets/images/bg_image.png
  - assets/images/rectangle_15.jpeg
  - assets/images/ellipse_3.jpeg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/image_1_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/ellipse_1_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/mobile_signal_1_x2.svg
  - assets/vectors/wifi_3_x2.svg
  - assets/images/rectangle_15.jpeg
  - assets/images/st.png
  - assets/images/shopping_cart_with_money.png
  - assets/images/ellipse_3.jpeg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/battery_3_x2.svg
  - assets/vectors/image_2_x2.svg
  - assets/vectors/mobile_signal_x2.svg
  - assets/vectors/ellipse_2_x2.svg
  - assets/vectors/wifi_2_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/images/rectangle_15.jpeg
  - assets/images/st.png
  - assets/images/ellipse_3.jpeg
  - assets/images/shopping_cart_with_money.png
  - assets/vectors/line_1_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/battery_4_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/line_2_x2.svg
  - assets/vectors/ellipse_31_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/mobile_signal_4_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/image_3_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/vectors/mobile_signal_2_x2.svg
  - assets/vectors/image_x2.svg
  - assets/images/ellipse_4.png
  - assets/vectors/ellipse_41_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/image_4_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/vectors/mobile_signal_3_x2.svg

